packages:
  - packages/*

catalogs:
  dev:
    '@eslint/config-inspector': ^1.2.0
    '@types/node': ^22.18.0
    cspell: ^9.2.0
    eslint: ^9.34.0
    knip: ^5.63.0
    prettier: ^3.6.2
    prettier-plugin-packagejson: ^2.5.19
    prettier-plugin-tailwindcss: ^0.6.14
    tsdown: ^0.14.2
    turbo: ^2.5.6
    typescript: ^5.9.2
  prod:
    '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
    '@eslint-react/eslint-plugin': ^1.52.6
    '@eslint/js': ^9.34.0
    '@next/eslint-plugin-next': ^15.5.2
    '@typescript-eslint/eslint-plugin': ^8.41.0
    '@typescript-eslint/parser': ^8.41.0
    '@vitest/eslint-plugin': ^1.3.4
    eslint-config-flat-gitignore: ^2.1.0
    eslint-config-prettier: ^10.1.8
    eslint-flat-config-utils: ^2.1.1
    eslint-plugin-better-tailwindcss: ^3.7.6
    eslint-plugin-command: ^3.3.1
    eslint-plugin-de-morgan: ^1.3.1
    eslint-plugin-import-lite: ^0.3.0
    eslint-plugin-jsdoc: ^54.1.1
    eslint-plugin-jsx-a11y: ^6.10.2
    eslint-plugin-n: ^17.21.3
    eslint-plugin-playwright: ^2.2.2
    eslint-plugin-prettier: ^5.5.4
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.20
    eslint-plugin-regexp: ^2.10.0
    eslint-plugin-simple-import-sort: ^12.1.1
    eslint-plugin-sonarjs: ^3.0.5
    eslint-plugin-unicorn: ^60.0.0
    eslint-plugin-unused-imports: ^4.2.0
    globals: ^16.3.0
    local-pkg: ^1.1.2
